---
- name: PHP App Deploy
  hosts: webservers
  vars:
    http_port: 80
  become: true
  
  tasks:
   - name: install apache2 
     apt: name=apache2 update_cache=yes state=latest
    
   - name: enabled mod_rewrite
     apache2_module: name=rewrite state=absent
     notify:
        - reload apache2
        
   - name: apache2 listen on port 80
     lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port }}" state=present
     notify:
        - reload apache2
   
   - name: copy code file 
     template:
        src: /home/ansible/index.html.j2
        dest: /var/www/html/index.html
    
  handlers:
   - name: reload apache2
     service: name=apache2 state=reloaded