---
- name: Sample Application Deployment
  hosts: webservers
  vars: 
        http_port: 80
  become: true

  tasks:
        - name: Install Apache2
          apt: name=apache2 update_cache=yes state=latest
          
        - name: Enable mode rewrite
          apache2_module: name=rewrite state=present
          notify:
               - restart apache2
        
        - name: apache port listen on 80
          lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen" line="Listen {{http_port}}" state=present
          notify:
               - restart apache2
                 
        - name: copy code file
          copy: 
               src: /home/ansible/index1.php
               dest: /var/www/html/index.php
               
  handlers:
        - name: restart apache2
          service: name=apache2 state=restarted